//
// Created by bian on 7/25/18.
//

#ifndef MACROLAB_ATOM_CONSTANTS_H
#define MACROLAB_ATOM_CONSTANTS_H

#include <string>
#include <map>

namespace biol
{
    namespace constants
    {

        // scoped enum class for type safety
        enum AtomTypes
        {
            e_C,
            e_CA,
            e_CB,
            e_CD,
            e_CD1,
            e_CD2,
            e_CE,
            e_CE1,
            e_CE2,
            e_CE3,
            e_CG,
            e_CG1,
            e_CG2,
            e_CH2,
            e_CZ,
            e_CZ2,
            e_CZ3,
            e_H,
            e_HA,
            e_HA2,
            e_HA3,
            e_HB,
            e_HB1,
            e_HB2,
            e_HB3,
            e_HD1,
            e_HD11,
            e_HD12,
            e_HD13,
            e_HD2,
            e_HD21,
            e_HD22,
            e_HD23,
            e_HD3,
            e_HE,
            e_HE1,
            e_HE2,
            e_HE21,
            e_HE22,
            e_HE3,
            e_HG,
            e_HG1,
            e_HG11,
            e_HG12,
            e_HG13,
            e_HG2,
            e_HG21,
            e_HG22,
            e_HG23,
            e_HG3,
            e_HH,
            e_HH11,
            e_HH12,
            e_HH2,
            e_HH21,
            e_HH22,
            e_HZ,
            e_HZ1,
            e_HZ2,
            e_HZ3,
            e_N,
            e_ND1,
            e_ND2,
            e_NE,
            e_NE1,
            e_NE2,
            e_NH1,
            e_NH2,
            e_NZ,
            e_O,
            e_OD1,
            e_OD2,
            e_OE1,
            e_OE2,
            e_OG,
            e_OG1,
            e_OH,
            e_SD,
            e_SG,
                i_number_of_atom_types
        };

        // enumerators of an scoped enumeration type are not automatically converted to an integral type
        const std::string PDB_ATOM_NAMES[i_number_of_atom_types] = {
            "C",
            "CA",
            "CB",
            "CD",
            "CD1",
            "CD2",
            "CE",
            "CE1",
            "CE2",
            "CE3",
            "CG",
            "CG1",
            "CG2",
            "CH2",
            "CZ",
            "CZ2",
            "CZ3",
            "H",
            "HA",
            "HA2",
            "HA3",
            "HB",
            "HB1",
            "HB2",
            "HB3",
            "HD1",
            "HD11",
            "HD12",
            "HD13",
            "HD2",
            "HD21",
            "HD22",
            "HD23",
            "HD3",
            "HE",
            "HE1",
            "HE2",
            "HE21",
            "HE22",
            "HE3",
            "HG",
            "HG1",
            "HG11",
            "HG12",
            "HG13",
            "HG2",
            "HG21",
            "HG22",
            "HG23",
            "HG3",
            "HH",
            "HH11",
            "HH12",
            "HH2",
            "HH21",
            "HH22",
            "HZ",
            "HZ1",
            "HZ2",
            "HZ3",
            "N",
            "ND1",
            "ND2",
            "NE",
            "NE1",
            "NE2",
            "NH1",
            "NH2",
            "NZ",
            "O",
            "OD1",
            "OD2",
            "OE1",
            "OE2",
            "OG",
            "OG1",
            "OH",
            "SD",
            "SG"
        };

        // atom types hashed by atom names
        const std::map<std::string, AtomTypes> ATOM_NAMES_TO_TYPES = {
            {"CA", e_CA},
            {"C", e_C},
            {"CB", e_CB},
            {"CD1", e_CD1},
            {"CD2", e_CD2},
            {"CD", e_CD},
            {"CE1", e_CE1},
            {"CE2", e_CE2},
            {"CE3", e_CE3},
            {"CE", e_CE},
            {"CG1", e_CG1},
            {"CG2", e_CG2},
            {"CG", e_CG},
            {"CH2", e_CH2},
            {"CZ2", e_CZ2},
            {"CZ3", e_CZ3},
            {"CZ", e_CZ},
            {"HA2", e_HA2},
            {"HA3", e_HA3},
            {"HA", e_HA},
            {"H", e_H},
            {"HB1", e_HB1},
            {"HB2", e_HB2},
            {"HB3", e_HB3},
            {"HB", e_HB},
            {"HD11", e_HD11},
            {"HD12", e_HD12},
            {"HD13", e_HD13},
            {"HD1", e_HD1},
            {"HD21", e_HD21},
            {"HD22", e_HD22},
            {"HD23", e_HD23},
            {"HD2", e_HD2},
            {"HD3", e_HD3},
            {"HE1", e_HE1},
            {"HE21", e_HE21},
            {"HE22", e_HE22},
            {"HE2", e_HE2},
            {"HE3", e_HE3},
            {"HE", e_HE},
            {"HG11", e_HG11},
            {"HG12", e_HG12},
            {"HG13", e_HG13},
            {"HG1", e_HG1},
            {"HG21", e_HG21},
            {"HG22", e_HG22},
            {"HG23", e_HG23},
            {"HG2", e_HG2},
            {"HG3", e_HG3},
            {"HG", e_HG},
            {"HH11", e_HH11},
            {"HH12", e_HH12},
            {"HH21", e_HH21},
            {"HH22", e_HH22},
            {"HH2", e_HH2},
            {"HH", e_HH},
            {"HZ1", e_HZ1},
            {"HZ2", e_HZ2},
            {"HZ3", e_HZ3},
            {"HZ", e_HZ},
            {"N", e_N},
            {"ND1", e_ND1},
            {"ND2", e_ND2},
            {"NE1", e_NE1},
            {"NE2", e_NE2},
            {"NE", e_NE},
            {"NH1", e_NH1},
            {"NH2", e_NH2},
            {"NZ", e_NZ},
            {"O", e_O},
            {"OD1", e_OD1},
            {"OD2", e_OD2},
            {"OE1", e_OE1},
            {"OE2", e_OE2},
            {"OG1", e_OG1},
            {"OG", e_OG},
            {"OH", e_OH},
            {"SD", e_SD},
            {"SG", e_SG}
        };
    }
}
#endif //MACROLAB_ATOM_CONSTANTS_H
